create table Skills (
	SkillId INT PRIMARY KEY,
	SkillDescription VARCHAR(50)
);
insert into Skills (SkillId, SkillDescription) values (1, 'RC Detailing');
insert into Skills (SkillId, SkillDescription) values (2, 'Honeywell DCS');
insert into Skills (SkillId, SkillDescription) values (3, 'SSD');
insert into Skills (SkillId, SkillDescription) values (4, 'Non-profit Program Development');
insert into Skills (SkillId, SkillDescription) values (5, 'PSD');
insert into Skills (SkillId, SkillDescription) values (6, 'SPSS');
insert into Skills (SkillId, SkillDescription) values (7, 'IBM Rational Tools');
insert into Skills (SkillId, SkillDescription) values (8, 'Yoga Instruction');
insert into Skills (SkillId, SkillDescription) values (9, 'LVDS');
insert into Skills (SkillId, SkillDescription) values (10, 'CMS');
insert into Skills (SkillId, SkillDescription) values (11, 'DNA Sequencing');
insert into Skills (SkillId, SkillDescription) values (12, 'Microsoft MVP');
insert into Skills (SkillId, SkillDescription) values (13, 'Key Account Development');
insert into Skills (SkillId, SkillDescription) values (14, 'NX-OS');
insert into Skills (SkillId, SkillDescription) values (15, 'Customer Retention');
insert into Skills (SkillId, SkillDescription) values (16, 'JPEG');
insert into Skills (SkillId, SkillDescription) values (17, 'SVM');
insert into Skills (SkillId, SkillDescription) values (18, 'Industrial Ethernet');
insert into Skills (SkillId, SkillDescription) values (19, 'GST');
insert into Skills (SkillId, SkillDescription) values (20, 'ILS');
insert into Skills (SkillId, SkillDescription) values (21, 'JSTOR');
insert into Skills (SkillId, SkillDescription) values (22, 'Drums');
insert into Skills (SkillId, SkillDescription) values (23, 'RC Detailing');
insert into Skills (SkillId, SkillDescription) values (24, 'SQLite');
insert into Skills (SkillId, SkillDescription) values (25, 'Qt');
insert into Skills (SkillId, SkillDescription) values (26, 'PDF Creator');
insert into Skills (SkillId, SkillDescription) values (27, 'Oligonucleotide Synthesis');
insert into Skills (SkillId, SkillDescription) values (28, 'Taleo');
insert into Skills (SkillId, SkillDescription) values (29, 'MSDS');
insert into Skills (SkillId, SkillDescription) values (30, 'Unreal Editor');
insert into Skills (SkillId, SkillDescription) values (31, 'CVM');
insert into Skills (SkillId, SkillDescription) values (32, 'Visio');
insert into Skills (SkillId, SkillDescription) values (33, 'SQR');
insert into Skills (SkillId, SkillDescription) values (34, 'DTMF');
insert into Skills (SkillId, SkillDescription) values (35, 'Location Intelligence');
insert into Skills (SkillId, SkillDescription) values (36, 'SAP ERP');
insert into Skills (SkillId, SkillDescription) values (37, 'RDC');
insert into Skills (SkillId, SkillDescription) values (38, 'Game Design');
insert into Skills (SkillId, SkillDescription) values (39, 'Start-ups Management');
insert into Skills (SkillId, SkillDescription) values (40, 'Aesthetic Surgery');
insert into Skills (SkillId, SkillDescription) values (41, 'XFS');
insert into Skills (SkillId, SkillDescription) values (42, 'Executive Management');
insert into Skills (SkillId, SkillDescription) values (43, 'UVLayout');
insert into Skills (SkillId, SkillDescription) values (44, 'GML');
insert into Skills (SkillId, SkillDescription) values (45, 'Business Ethics');
insert into Skills (SkillId, SkillDescription) values (46, 'RC');
insert into Skills (SkillId, SkillDescription) values (47, 'SNMP');
insert into Skills (SkillId, SkillDescription) values (48, 'International Business');
insert into Skills (SkillId, SkillDescription) values (49, 'OEM contracts');
insert into Skills (SkillId, SkillDescription) values (50, 'Bathrooms');
insert into Skills (SkillId, SkillDescription) values (51, 'CFTC');
insert into Skills (SkillId, SkillDescription) values (52, 'CQ');
insert into Skills (SkillId, SkillDescription) values (53, 'Store Operations');
insert into Skills (SkillId, SkillDescription) values (54, 'CTD');
insert into Skills (SkillId, SkillDescription) values (55, 'LaTeX');
insert into Skills (SkillId, SkillDescription) values (56, 'Flight Training');
insert into Skills (SkillId, SkillDescription) values (57, 'Gifts');
insert into Skills (SkillId, SkillDescription) values (58, 'SGML');
insert into Skills (SkillId, SkillDescription) values (59, 'DTI');
insert into Skills (SkillId, SkillDescription) values (60, 'Youth Development');
insert into Skills (SkillId, SkillDescription) values (61, 'Snow Leopard');
insert into Skills (SkillId, SkillDescription) values (62, 'RSpec');
insert into Skills (SkillId, SkillDescription) values (63, 'Document Imaging');
insert into Skills (SkillId, SkillDescription) values (64, 'IEX');
insert into Skills (SkillId, SkillDescription) values (65, 'GTS');
insert into Skills (SkillId, SkillDescription) values (66, 'Essbase');
insert into Skills (SkillId, SkillDescription) values (67, 'Observational Astronomy');
insert into Skills (SkillId, SkillDescription) values (68, 'DCP');
insert into Skills (SkillId, SkillDescription) values (69, 'International Sales');
insert into Skills (SkillId, SkillDescription) values (70, 'Juvenile Delinquency');
insert into Skills (SkillId, SkillDescription) values (71, 'VC#');
insert into Skills (SkillId, SkillDescription) values (72, 'EMS');
insert into Skills (SkillId, SkillDescription) values (73, 'Dysarthria');
insert into Skills (SkillId, SkillDescription) values (74, 'Steam Turbines');
insert into Skills (SkillId, SkillDescription) values (75, 'RF Design');
insert into Skills (SkillId, SkillDescription) values (76, 'Vaccines');
insert into Skills (SkillId, SkillDescription) values (77, 'Gstreamer');
insert into Skills (SkillId, SkillDescription) values (78, 'VSD');
insert into Skills (SkillId, SkillDescription) values (79, 'SDLX');
insert into Skills (SkillId, SkillDescription) values (80, 'TMAP');
insert into Skills (SkillId, SkillDescription) values (81, 'HDCAM');
insert into Skills (SkillId, SkillDescription) values (82, 'TSM Administration');
insert into Skills (SkillId, SkillDescription) values (83, 'Gnome');
insert into Skills (SkillId, SkillDescription) values (84, 'Rock Music');
insert into Skills (SkillId, SkillDescription) values (85, 'FBCB2');
insert into Skills (SkillId, SkillDescription) values (86, 'Epoxy');
insert into Skills (SkillId, SkillDescription) values (87, 'Target Costing');
insert into Skills (SkillId, SkillDescription) values (88, 'Airports');
insert into Skills (SkillId, SkillDescription) values (89, 'MBAL');
insert into Skills (SkillId, SkillDescription) values (90, 'LDAR');
insert into Skills (SkillId, SkillDescription) values (91, 'Revenue Cycle Management');
insert into Skills (SkillId, SkillDescription) values (92, 'NWDI');
insert into Skills (SkillId, SkillDescription) values (93, 'Market Planning');
insert into Skills (SkillId, SkillDescription) values (94, 'TPP');
insert into Skills (SkillId, SkillDescription) values (95, 'VCM');
insert into Skills (SkillId, SkillDescription) values (96, 'Rock Climbing');
insert into Skills (SkillId, SkillDescription) values (97, 'PPC');
insert into Skills (SkillId, SkillDescription) values (98, 'IEC 61850');
insert into Skills (SkillId, SkillDescription) values (99, 'FSI');
insert into Skills (SkillId, SkillDescription) values (100, 'MQC');
insert into Skills (SkillId, SkillDescription) values (101, 'NPV');
insert into Skills (SkillId, SkillDescription) values (102, 'HTML Scripting');
insert into Skills (SkillId, SkillDescription) values (103, 'First Time Home Buyers');
insert into Skills (SkillId, SkillDescription) values (104, 'Yield');
insert into Skills (SkillId, SkillDescription) values (105, 'Theatre');
insert into Skills (SkillId, SkillDescription) values (106, 'MRIS');
insert into Skills (SkillId, SkillDescription) values (107, 'DMZ');
insert into Skills (SkillId, SkillDescription) values (108, 'SOA');
insert into Skills (SkillId, SkillDescription) values (109, 'OSHA');
insert into Skills (SkillId, SkillDescription) values (110, 'Oncology');
insert into Skills (SkillId, SkillDescription) values (111, 'US Tax');
insert into Skills (SkillId, SkillDescription) values (112, 'ISO');
insert into Skills (SkillId, SkillDescription) values (113, 'AutoCAD');
insert into Skills (SkillId, SkillDescription) values (114, 'DMRB');
insert into Skills (SkillId, SkillDescription) values (115, 'Team Building');
insert into Skills (SkillId, SkillDescription) values (116, 'Young Adults');
insert into Skills (SkillId, SkillDescription) values (117, 'Start-ups');
insert into Skills (SkillId, SkillDescription) values (118, 'Petroleum');
insert into Skills (SkillId, SkillDescription) values (119, 'Cost Efficiency');
insert into Skills (SkillId, SkillDescription) values (120, 'Hazardous Materials');
insert into Skills (SkillId, SkillDescription) values (121, 'OO Software Development');
insert into Skills (SkillId, SkillDescription) values (122, 'Localization');
insert into Skills (SkillId, SkillDescription) values (123, 'Kinesio Taping');
insert into Skills (SkillId, SkillDescription) values (124, 'Xbox One');
insert into Skills (SkillId, SkillDescription) values (125, 'RPG III');
insert into Skills (SkillId, SkillDescription) values (126, 'RBI');
insert into Skills (SkillId, SkillDescription) values (127, 'Hypertension');
insert into Skills (SkillId, SkillDescription) values (128, 'PCIe');
insert into Skills (SkillId, SkillDescription) values (129, 'Social Media');
insert into Skills (SkillId, SkillDescription) values (130, 'RP');
insert into Skills (SkillId, SkillDescription) values (131, 'RVM');
insert into Skills (SkillId, SkillDescription) values (132, 'HP QTP');
insert into Skills (SkillId, SkillDescription) values (133, 'MPages');
insert into Skills (SkillId, SkillDescription) values (134, 'Digital Signal Processors');
insert into Skills (SkillId, SkillDescription) values (135, 'OOAD');
insert into Skills (SkillId, SkillDescription) values (136, 'International Political Economy');
insert into Skills (SkillId, SkillDescription) values (137, 'GNU C++');
insert into Skills (SkillId, SkillDescription) values (138, 'SQL PL');
insert into Skills (SkillId, SkillDescription) values (139, 'Consulting');
insert into Skills (SkillId, SkillDescription) values (140, 'Www');
insert into Skills (SkillId, SkillDescription) values (141, 'Variable Frequency Drives');
insert into Skills (SkillId, SkillDescription) values (142, 'Modeling');
insert into Skills (SkillId, SkillDescription) values (143, 'CNN Pathfire');
insert into Skills (SkillId, SkillDescription) values (144, 'PKCS');
insert into Skills (SkillId, SkillDescription) values (145, 'Rubber');
insert into Skills (SkillId, SkillDescription) values (146, 'Yeast two-hybrid');
insert into Skills (SkillId, SkillDescription) values (147, 'Art History');
insert into Skills (SkillId, SkillDescription) values (148, 'BSSAP');
insert into Skills (SkillId, SkillDescription) values (149, 'HBDI');
insert into Skills (SkillId, SkillDescription) values (150, 'JNDI');
insert into Skills (SkillId, SkillDescription) values (151, 'Pilates');
insert into Skills (SkillId, SkillDescription) values (152, 'MRB');
insert into Skills (SkillId, SkillDescription) values (153, 'RFP');
insert into Skills (SkillId, SkillDescription) values (154, 'International Logistics');
insert into Skills (SkillId, SkillDescription) values (155, 'Offshore Outsourcing');
insert into Skills (SkillId, SkillDescription) values (156, 'CNC Programing');
insert into Skills (SkillId, SkillDescription) values (157, 'LTSpice');
insert into Skills (SkillId, SkillDescription) values (158, 'EBMS');
insert into Skills (SkillId, SkillDescription) values (159, 'Behavior Management');
insert into Skills (SkillId, SkillDescription) values (160, 'DVD Architect');
insert into Skills (SkillId, SkillDescription) values (161, 'Fashion');
insert into Skills (SkillId, SkillDescription) values (162, 'HNW');
insert into Skills (SkillId, SkillDescription) values (163, 'Medical Nutrition Therapy');
insert into Skills (SkillId, SkillDescription) values (164, 'Digital Imaging');
insert into Skills (SkillId, SkillDescription) values (165, 'Electronic Trading');
insert into Skills (SkillId, SkillDescription) values (166, 'Satellite TV');
insert into Skills (SkillId, SkillDescription) values (167, 'YAML');
insert into Skills (SkillId, SkillDescription) values (168, 'Sleep Apnea');
insert into Skills (SkillId, SkillDescription) values (169, 'WordPerfect');
insert into Skills (SkillId, SkillDescription) values (170, 'Zeolites');
insert into Skills (SkillId, SkillDescription) values (171, 'IBM Rational Rhapsody');
insert into Skills (SkillId, SkillDescription) values (172, 'MPLAB');
insert into Skills (SkillId, SkillDescription) values (173, 'Differentiated Instruction');
insert into Skills (SkillId, SkillDescription) values (174, 'System Administration');
insert into Skills (SkillId, SkillDescription) values (175, 'Microsoft Dynamics NAV');
insert into Skills (SkillId, SkillDescription) values (176, 'FBT');
insert into Skills (SkillId, SkillDescription) values (177, 'Cisco VoIP');
insert into Skills (SkillId, SkillDescription) values (178, 'Broadband');
insert into Skills (SkillId, SkillDescription) values (179, 'Claim');
insert into Skills (SkillId, SkillDescription) values (180, 'Yellow Belt');
insert into Skills (SkillId, SkillDescription) values (181, 'Whole House Renovations');
insert into Skills (SkillId, SkillDescription) values (182, 'JAX-RPC');
insert into Skills (SkillId, SkillDescription) values (183, 'Juniper Technologies');
insert into Skills (SkillId, SkillDescription) values (184, 'TWIC Card');
insert into Skills (SkillId, SkillDescription) values (185, 'Jenark');
insert into Skills (SkillId, SkillDescription) values (186, 'Oz Principle');
insert into Skills (SkillId, SkillDescription) values (187, 'PCI DSS');
insert into Skills (SkillId, SkillDescription) values (188, 'AXE');
insert into Skills (SkillId, SkillDescription) values (189, 'Clinical Research');
insert into Skills (SkillId, SkillDescription) values (190, 'OWASP');
insert into Skills (SkillId, SkillDescription) values (191, 'Military Aviation');
insert into Skills (SkillId, SkillDescription) values (192, 'Easements');
insert into Skills (SkillId, SkillDescription) values (193, 'Interest Rate Swaps');
insert into Skills (SkillId, SkillDescription) values (194, 'Yard Signs');
insert into Skills (SkillId, SkillDescription) values (195, 'Transportation');
insert into Skills (SkillId, SkillDescription) values (196, 'LSP');
insert into Skills (SkillId, SkillDescription) values (197, 'Jets');
insert into Skills (SkillId, SkillDescription) values (198, 'FDT');
insert into Skills (SkillId, SkillDescription) values (199, 'Twilio');
insert into Skills (SkillId, SkillDescription) values (200, 'RHIT');
insert into Skills (SkillId, SkillDescription) values (201, 'EBR');
insert into Skills (SkillId, SkillDescription) values (202, 'Lyris');
insert into Skills (SkillId, SkillDescription) values (203, 'PY');
insert into Skills (SkillId, SkillDescription) values (204, 'XML Schema');
insert into Skills (SkillId, SkillDescription) values (205, 'Rhapsody');
insert into Skills (SkillId, SkillDescription) values (206, 'Media TV');
insert into Skills (SkillId, SkillDescription) values (207, 'LLBLGen Pro');
insert into Skills (SkillId, SkillDescription) values (208, 'JConsole');
insert into Skills (SkillId, SkillDescription) values (209, 'DTT');
insert into Skills (SkillId, SkillDescription) values (210, 'TWiki');
insert into Skills (SkillId, SkillDescription) values (211, 'Cisco MDS SAN switches');
insert into Skills (SkillId, SkillDescription) values (212, 'LPAR');
insert into Skills (SkillId, SkillDescription) values (213, 'TSP');
insert into Skills (SkillId, SkillDescription) values (214, 'PVST+');
insert into Skills (SkillId, SkillDescription) values (215, 'SAP PS');
insert into Skills (SkillId, SkillDescription) values (216, 'Airports');
insert into Skills (SkillId, SkillDescription) values (217, 'BPO');
insert into Skills (SkillId, SkillDescription) values (218, 'HST');
insert into Skills (SkillId, SkillDescription) values (219, 'WDK');
insert into Skills (SkillId, SkillDescription) values (220, 'TCM');
insert into Skills (SkillId, SkillDescription) values (221, 'eGain');
insert into Skills (SkillId, SkillDescription) values (222, 'Interviews');
insert into Skills (SkillId, SkillDescription) values (223, 'Church Growth');
insert into Skills (SkillId, SkillDescription) values (224, 'FCE');
insert into Skills (SkillId, SkillDescription) values (225, 'LMS Test.Lab');
insert into Skills (SkillId, SkillDescription) values (226, 'Full SDLC');
insert into Skills (SkillId, SkillDescription) values (227, 'Efficent');
insert into Skills (SkillId, SkillDescription) values (228, 'Enzyme Kinetics');
insert into Skills (SkillId, SkillDescription) values (229, 'NICU');
insert into Skills (SkillId, SkillDescription) values (230, 'HP Servers');
insert into Skills (SkillId, SkillDescription) values (231, 'SBEM');
insert into Skills (SkillId, SkillDescription) values (232, 'ESB');
insert into Skills (SkillId, SkillDescription) values (233, 'Egyptology');
insert into Skills (SkillId, SkillDescription) values (234, 'Vocational Rehabilitation');
insert into Skills (SkillId, SkillDescription) values (235, 'GNS3');
insert into Skills (SkillId, SkillDescription) values (236, 'WordPerfect');
insert into Skills (SkillId, SkillDescription) values (237, 'Owner Representation');
insert into Skills (SkillId, SkillDescription) values (238, 'Blues');
insert into Skills (SkillId, SkillDescription) values (239, 'VTL');
insert into Skills (SkillId, SkillDescription) values (240, 'Business Process');
insert into Skills (SkillId, SkillDescription) values (241, 'Play by Play');
insert into Skills (SkillId, SkillDescription) values (242, 'OMNI');
insert into Skills (SkillId, SkillDescription) values (243, 'RTL Coding');
insert into Skills (SkillId, SkillDescription) values (244, 'Kettlebells');
insert into Skills (SkillId, SkillDescription) values (245, 'Guardianship');
insert into Skills (SkillId, SkillDescription) values (246, 'Distance Learning');
insert into Skills (SkillId, SkillDescription) values (247, 'XPS');
insert into Skills (SkillId, SkillDescription) values (248, 'Information Architecture');
insert into Skills (SkillId, SkillDescription) values (249, 'JSTOR');
insert into Skills (SkillId, SkillDescription) values (250, 'Hyperion EPM');
insert into Skills (SkillId, SkillDescription) values (251, 'Grievances');
insert into Skills (SkillId, SkillDescription) values (252, 'Joint Ventures');
insert into Skills (SkillId, SkillDescription) values (253, 'EBITDA Growth');
insert into Skills (SkillId, SkillDescription) values (254, 'TCO reduction');
insert into Skills (SkillId, SkillDescription) values (255, 'Ultrasound');
insert into Skills (SkillId, SkillDescription) values (256, 'PVST+');
insert into Skills (SkillId, SkillDescription) values (257, 'Warranty');
insert into Skills (SkillId, SkillDescription) values (258, 'International Relations');
insert into Skills (SkillId, SkillDescription) values (259, '10 Key');
insert into Skills (SkillId, SkillDescription) values (260, 'Canon DSLR');
insert into Skills (SkillId, SkillDescription) values (261, 'Objective-C');
insert into Skills (SkillId, SkillDescription) values (262, 'MRB');
insert into Skills (SkillId, SkillDescription) values (263, 'NDM');
insert into Skills (SkillId, SkillDescription) values (264, 'Business Object');
insert into Skills (SkillId, SkillDescription) values (265, 'Blackberry');
insert into Skills (SkillId, SkillDescription) values (266, 'Agilent ADS');
insert into Skills (SkillId, SkillDescription) values (267, 'Sh');
insert into Skills (SkillId, SkillDescription) values (268, 'NS-2');
insert into Skills (SkillId, SkillDescription) values (269, 'Doors');
insert into Skills (SkillId, SkillDescription) values (270, 'HUMINT');
insert into Skills (SkillId, SkillDescription) values (271, 'Family Therapy');
insert into Skills (SkillId, SkillDescription) values (272, 'QMF for Windows');
insert into Skills (SkillId, SkillDescription) values (273, 'Whitewater Kayaking');
insert into Skills (SkillId, SkillDescription) values (274, 'NDDS');
insert into Skills (SkillId, SkillDescription) values (275, 'FCC License');
insert into Skills (SkillId, SkillDescription) values (276, 'Sleepwear');
insert into Skills (SkillId, SkillDescription) values (277, 'VNA');
insert into Skills (SkillId, SkillDescription) values (278, 'Capacity Utilization');
insert into Skills (SkillId, SkillDescription) values (279, 'Urban Economics');
insert into Skills (SkillId, SkillDescription) values (280, 'UV/Vis');
insert into Skills (SkillId, SkillDescription) values (281, 'ABS');
insert into Skills (SkillId, SkillDescription) values (282, 'Turn Around Management');
insert into Skills (SkillId, SkillDescription) values (283, 'AP Style');
insert into Skills (SkillId, SkillDescription) values (284, 'BMC Portal');
insert into Skills (SkillId, SkillDescription) values (285, 'Occupational Health');
insert into Skills (SkillId, SkillDescription) values (286, 'Keyword Research');
insert into Skills (SkillId, SkillDescription) values (287, 'Oxides');
insert into Skills (SkillId, SkillDescription) values (288, 'Fertility');
insert into Skills (SkillId, SkillDescription) values (289, 'IBM iSeries');
insert into Skills (SkillId, SkillDescription) values (290, 'CQA');
insert into Skills (SkillId, SkillDescription) values (291, 'Geomatics');
insert into Skills (SkillId, SkillDescription) values (292, 'SharePoint Server');
insert into Skills (SkillId, SkillDescription) values (293, 'AHDL');
insert into Skills (SkillId, SkillDescription) values (294, 'XHTML');
insert into Skills (SkillId, SkillDescription) values (295, 'UBD');
insert into Skills (SkillId, SkillDescription) values (296, 'MySQL Cluster');
insert into Skills (SkillId, SkillDescription) values (297, 'iPhoto');
insert into Skills (SkillId, SkillDescription) values (298, 'YUM');
insert into Skills (SkillId, SkillDescription) values (299, 'Business Development');
insert into Skills (SkillId, SkillDescription) values (300, 'TPX');
insert into Skills (SkillId, SkillDescription) values (301, 'KPO');
insert into Skills (SkillId, SkillDescription) values (302, 'Food');
insert into Skills (SkillId, SkillDescription) values (303, 'Health Economics');
insert into Skills (SkillId, SkillDescription) values (304, 'DDI');
insert into Skills (SkillId, SkillDescription) values (305, 'GIS');
insert into Skills (SkillId, SkillDescription) values (306, 'Digital Strategy');
insert into Skills (SkillId, SkillDescription) values (307, 'Zuora');
insert into Skills (SkillId, SkillDescription) values (308, 'Omgeo Oasys');
insert into Skills (SkillId, SkillDescription) values (309, 'Legal Research');
insert into Skills (SkillId, SkillDescription) values (310, 'Applicant Tracking Systems');
insert into Skills (SkillId, SkillDescription) values (311, 'GIMP');
insert into Skills (SkillId, SkillDescription) values (312, 'Pyramid');
insert into Skills (SkillId, SkillDescription) values (313, 'LGBT Rights');
insert into Skills (SkillId, SkillDescription) values (314, 'Komodo');
insert into Skills (SkillId, SkillDescription) values (315, 'Bloomberg Terminal');
insert into Skills (SkillId, SkillDescription) values (316, 'NCP');
insert into Skills (SkillId, SkillDescription) values (317, 'gSOAP');
insert into Skills (SkillId, SkillDescription) values (318, 'Record Keeping');
insert into Skills (SkillId, SkillDescription) values (319, 'RNAseq');
insert into Skills (SkillId, SkillDescription) values (320, 'NDC');
insert into Skills (SkillId, SkillDescription) values (321, 'Wyse');
insert into Skills (SkillId, SkillDescription) values (322, 'Digital Electronics');
insert into Skills (SkillId, SkillDescription) values (323, 'IT Service Management');
insert into Skills (SkillId, SkillDescription) values (324, 'McKesson STAR');
insert into Skills (SkillId, SkillDescription) values (325, 'Equities');
insert into Skills (SkillId, SkillDescription) values (326, 'Robotics');
insert into Skills (SkillId, SkillDescription) values (327, 'EU Law');
insert into Skills (SkillId, SkillDescription) values (328, 'Web Typography');
insert into Skills (SkillId, SkillDescription) values (329, 'uDig');
insert into Skills (SkillId, SkillDescription) values (330, 'GMP');
insert into Skills (SkillId, SkillDescription) values (331, 'PVM');
insert into Skills (SkillId, SkillDescription) values (332, 'TDP');
insert into Skills (SkillId, SkillDescription) values (333, 'Art Exhibitions');
insert into Skills (SkillId, SkillDescription) values (334, 'IBM Servers');
insert into Skills (SkillId, SkillDescription) values (335, 'Xdebug');
insert into Skills (SkillId, SkillDescription) values (336, 'GBA');
insert into Skills (SkillId, SkillDescription) values (337, 'Ocular Disease');
insert into Skills (SkillId, SkillDescription) values (338, 'Yardi Property Management');
insert into Skills (SkillId, SkillDescription) values (339, 'Shrinkage');
insert into Skills (SkillId, SkillDescription) values (340, 'Risk Management');
insert into Skills (SkillId, SkillDescription) values (341, 'IT Recruitment');
insert into Skills (SkillId, SkillDescription) values (342, 'Eagle PCB');
insert into Skills (SkillId, SkillDescription) values (343, 'AQTF compliance');
insert into Skills (SkillId, SkillDescription) values (344, 'IPTV');
insert into Skills (SkillId, SkillDescription) values (345, 'ALM');
insert into Skills (SkillId, SkillDescription) values (346, 'Civil Litigation');
insert into Skills (SkillId, SkillDescription) values (347, 'iPad Development');
insert into Skills (SkillId, SkillDescription) values (348, 'SEP IRA');
insert into Skills (SkillId, SkillDescription) values (349, 'Alternative Dispute Resolution');
insert into Skills (SkillId, SkillDescription) values (350, 'Eyebrow');
insert into Skills (SkillId, SkillDescription) values (351, 'PFS');
insert into Skills (SkillId, SkillDescription) values (352, 'Lucene');
insert into Skills (SkillId, SkillDescription) values (353, 'Commercial Awareness');
insert into Skills (SkillId, SkillDescription) values (354, 'Omnis');
insert into Skills (SkillId, SkillDescription) values (355, 'JNI');
insert into Skills (SkillId, SkillDescription) values (356, 'AACR2');
insert into Skills (SkillId, SkillDescription) values (357, 'Tax Preparation');
insert into Skills (SkillId, SkillDescription) values (358, 'VDA');
insert into Skills (SkillId, SkillDescription) values (359, 'Online Advertising');
insert into Skills (SkillId, SkillDescription) values (360, 'MDA');
insert into Skills (SkillId, SkillDescription) values (361, 'Virtual PC');
insert into Skills (SkillId, SkillDescription) values (362, 'Nitrous Oxide');
insert into Skills (SkillId, SkillDescription) values (363, 'CSCP');
insert into Skills (SkillId, SkillDescription) values (364, 'HD Video');
insert into Skills (SkillId, SkillDescription) values (365, 'System Deployment');
insert into Skills (SkillId, SkillDescription) values (366, 'TIG Welding');
insert into Skills (SkillId, SkillDescription) values (367, 'Interactive Whiteboard');
insert into Skills (SkillId, SkillDescription) values (368, 'TNCC Instruction');
insert into Skills (SkillId, SkillDescription) values (369, 'Family Therapy');
insert into Skills (SkillId, SkillDescription) values (370, 'Visual Identity Design');
insert into Skills (SkillId, SkillDescription) values (371, 'Downstream Oil &amp; Gas');
insert into Skills (SkillId, SkillDescription) values (372, 'Eyebrow');
insert into Skills (SkillId, SkillDescription) values (373, 'Diagnostic Ultrasound');
insert into Skills (SkillId, SkillDescription) values (374, 'CSG');
insert into Skills (SkillId, SkillDescription) values (375, 'PLC');
insert into Skills (SkillId, SkillDescription) values (376, 'RNAi');
insert into Skills (SkillId, SkillDescription) values (377, 'Plant Identification');
insert into Skills (SkillId, SkillDescription) values (378, 'Requirements Gathering');
insert into Skills (SkillId, SkillDescription) values (379, 'SBS');
insert into Skills (SkillId, SkillDescription) values (380, 'RFQ Development');
insert into Skills (SkillId, SkillDescription) values (381, 'Zebra');
insert into Skills (SkillId, SkillDescription) values (382, 'JavaSE');
insert into Skills (SkillId, SkillDescription) values (383, 'Urban Infill');
insert into Skills (SkillId, SkillDescription) values (384, 'Earned Value Management');
insert into Skills (SkillId, SkillDescription) values (385, 'DP');
insert into Skills (SkillId, SkillDescription) values (386, 'MKS Integrity');
insert into Skills (SkillId, SkillDescription) values (387, 'Hyperion EPM');
insert into Skills (SkillId, SkillDescription) values (388, 'OS/400');
insert into Skills (SkillId, SkillDescription) values (389, '3D Modeling');
insert into Skills (SkillId, SkillDescription) values (390, 'Cement');
insert into Skills (SkillId, SkillDescription) values (391, 'Holistic Health');
insert into Skills (SkillId, SkillDescription) values (392, 'Process Improvement');
insert into Skills (SkillId, SkillDescription) values (393, 'Security Operations');
insert into Skills (SkillId, SkillDescription) values (394, 'QoS');
insert into Skills (SkillId, SkillDescription) values (395, 'OODBMS');
insert into Skills (SkillId, SkillDescription) values (396, 'Bridge');
insert into Skills (SkillId, SkillDescription) values (397, 'International HR');
insert into Skills (SkillId, SkillDescription) values (398, 'Vendor Relations');
insert into Skills (SkillId, SkillDescription) values (399, 'CCP');
insert into Skills (SkillId, SkillDescription) values (400, 'Kinematics');
insert into Skills (SkillId, SkillDescription) values (401, 'Knee');
insert into Skills (SkillId, SkillDescription) values (402, 'Eyebrow');
insert into Skills (SkillId, SkillDescription) values (403, 'Photos');
insert into Skills (SkillId, SkillDescription) values (404, 'CCVP');
insert into Skills (SkillId, SkillDescription) values (405, 'MXML');
insert into Skills (SkillId, SkillDescription) values (406, 'Environmental Science');
insert into Skills (SkillId, SkillDescription) values (407, 'OJEU');
insert into Skills (SkillId, SkillDescription) values (408, 'XML Spy');
insert into Skills (SkillId, SkillDescription) values (409, 'Team Effectiveness');
insert into Skills (SkillId, SkillDescription) values (410, 'Make vs Buy');
insert into Skills (SkillId, SkillDescription) values (411, 'JCIDS');
insert into Skills (SkillId, SkillDescription) values (412, 'LSP');
insert into Skills (SkillId, SkillDescription) values (413, 'HtmlUnit');
insert into Skills (SkillId, SkillDescription) values (414, 'Smartphones');
insert into Skills (SkillId, SkillDescription) values (415, 'Geography');
insert into Skills (SkillId, SkillDescription) values (416, 'HP QTP');
insert into Skills (SkillId, SkillDescription) values (417, 'Global Business Development');
insert into Skills (SkillId, SkillDescription) values (418, 'Key Account Development');
insert into Skills (SkillId, SkillDescription) values (419, 'Data Mining');
insert into Skills (SkillId, SkillDescription) values (420, 'JP54');
insert into Skills (SkillId, SkillDescription) values (421, 'Outdoor Education');
insert into Skills (SkillId, SkillDescription) values (422, 'PCR Primer Design');
insert into Skills (SkillId, SkillDescription) values (423, 'IFS ERP');
insert into Skills (SkillId, SkillDescription) values (424, 'ISO 22000');
insert into Skills (SkillId, SkillDescription) values (425, 'Crisis Management');
insert into Skills (SkillId, SkillDescription) values (426, 'Parts');
insert into Skills (SkillId, SkillDescription) values (427, 'NGP');
insert into Skills (SkillId, SkillDescription) values (428, 'Euroclear');
insert into Skills (SkillId, SkillDescription) values (429, 'Agriculture');
insert into Skills (SkillId, SkillDescription) values (430, 'FCIP');
insert into Skills (SkillId, SkillDescription) values (431, 'Rig');
insert into Skills (SkillId, SkillDescription) values (432, 'Motivational Speaking');
insert into Skills (SkillId, SkillDescription) values (433, 'Systems Engineering');
insert into Skills (SkillId, SkillDescription) values (434, 'ILT');
insert into Skills (SkillId, SkillDescription) values (435, 'MHE');
insert into Skills (SkillId, SkillDescription) values (436, 'First Time Home Sellers');
insert into Skills (SkillId, SkillDescription) values (437, 'Oceanography');
insert into Skills (SkillId, SkillDescription) values (438, 'Epicor');
insert into Skills (SkillId, SkillDescription) values (439, 'FDTD');
insert into Skills (SkillId, SkillDescription) values (440, 'UIX');
insert into Skills (SkillId, SkillDescription) values (441, 'Drums');
insert into Skills (SkillId, SkillDescription) values (442, 'Genetics');
insert into Skills (SkillId, SkillDescription) values (443, 'Biostatistics');
insert into Skills (SkillId, SkillDescription) values (444, 'DCAA');
insert into Skills (SkillId, SkillDescription) values (445, 'HR Transformation');
insert into Skills (SkillId, SkillDescription) values (446, 'HCS');
insert into Skills (SkillId, SkillDescription) values (447, 'DFT Compiler');
insert into Skills (SkillId, SkillDescription) values (448, 'Interactive Whiteboard');
insert into Skills (SkillId, SkillDescription) values (449, 'Image Manipulation');
insert into Skills (SkillId, SkillDescription) values (450, 'TV Production');
insert into Skills (SkillId, SkillDescription) values (451, 'Location Intelligence');
insert into Skills (SkillId, SkillDescription) values (452, 'RIP');
insert into Skills (SkillId, SkillDescription) values (453, 'Rugby Union');
insert into Skills (SkillId, SkillDescription) values (454, 'Biology');
insert into Skills (SkillId, SkillDescription) values (455, 'HFC');
insert into Skills (SkillId, SkillDescription) values (456, 'VMI Programs');
insert into Skills (SkillId, SkillDescription) values (457, 'EFQM Excellence Model');
insert into Skills (SkillId, SkillDescription) values (458, 'Jetty');
insert into Skills (SkillId, SkillDescription) values (459, 'MDL');
insert into Skills (SkillId, SkillDescription) values (460, 'GMI');
insert into Skills (SkillId, SkillDescription) values (461, 'PV');
insert into Skills (SkillId, SkillDescription) values (462, 'Heavy Equipment');
insert into Skills (SkillId, SkillDescription) values (463, 'Analysis');
insert into Skills (SkillId, SkillDescription) values (464, 'MMI');
insert into Skills (SkillId, SkillDescription) values (465, 'DTD');
insert into Skills (SkillId, SkillDescription) values (466, 'RTLS');
insert into Skills (SkillId, SkillDescription) values (467, 'HSIA');
insert into Skills (SkillId, SkillDescription) values (468, 'TDI');
insert into Skills (SkillId, SkillDescription) values (469, 'Business Intelligence');
insert into Skills (SkillId, SkillDescription) values (470, 'RS232');
insert into Skills (SkillId, SkillDescription) values (471, 'XBR');
insert into Skills (SkillId, SkillDescription) values (472, 'E-commerce');
insert into Skills (SkillId, SkillDescription) values (473, 'HD Video');
insert into Skills (SkillId, SkillDescription) values (474, 'Agarose Gel Electrophoresis');
insert into Skills (SkillId, SkillDescription) values (475, 'Drywall');
insert into Skills (SkillId, SkillDescription) values (476, 'Cold Calling');
insert into Skills (SkillId, SkillDescription) values (477, 'Substance Use Disorders');
insert into Skills (SkillId, SkillDescription) values (478, 'Ozone');
insert into Skills (SkillId, SkillDescription) values (479, 'SD');
insert into Skills (SkillId, SkillDescription) values (480, 'iView');
insert into Skills (SkillId, SkillDescription) values (481, 'Eclipse RCP');
insert into Skills (SkillId, SkillDescription) values (482, 'Onshore');
insert into Skills (SkillId, SkillDescription) values (483, 'Supply Chain Management');
insert into Skills (SkillId, SkillDescription) values (484, 'Real Estate License');
insert into Skills (SkillId, SkillDescription) values (485, 'Big Box');
insert into Skills (SkillId, SkillDescription) values (486, 'VSOE');
insert into Skills (SkillId, SkillDescription) values (487, 'Knee Surgery');
insert into Skills (SkillId, SkillDescription) values (488, 'Kitchen Remodeling');
insert into Skills (SkillId, SkillDescription) values (489, 'ODS');
insert into Skills (SkillId, SkillDescription) values (490, 'cGLP');
insert into Skills (SkillId, SkillDescription) values (491, 'RF');
insert into Skills (SkillId, SkillDescription) values (492, 'Civil Rights');
insert into Skills (SkillId, SkillDescription) values (493, 'KT');
insert into Skills (SkillId, SkillDescription) values (494, 'Quality Management');
insert into Skills (SkillId, SkillDescription) values (495, 'Electronic Payments');
insert into Skills (SkillId, SkillDescription) values (496, 'ICP');
insert into Skills (SkillId, SkillDescription) values (497, 'Xara');
insert into Skills (SkillId, SkillDescription) values (498, 'Environmental Impact Assessment');
insert into Skills (SkillId, SkillDescription) values (499, 'Client Relations');
insert into Skills (SkillId, SkillDescription) values (500, 'Piping');
insert into Skills (SkillId, SkillDescription) values (501, 'Scheduling');
insert into Skills (SkillId, SkillDescription) values (502, 'Subcontracting');
insert into Skills (SkillId, SkillDescription) values (503, 'Overseas Experience');
insert into Skills (SkillId, SkillDescription) values (504, 'BFD');
insert into Skills (SkillId, SkillDescription) values (505, 'Java Enterprise Edition');
insert into Skills (SkillId, SkillDescription) values (506, 'HDRI');
insert into Skills (SkillId, SkillDescription) values (507, 'Life Insurance');
insert into Skills (SkillId, SkillDescription) values (508, 'Protein Expression');
insert into Skills (SkillId, SkillDescription) values (509, 'RMA');
insert into Skills (SkillId, SkillDescription) values (510, 'EBR');
insert into Skills (SkillId, SkillDescription) values (511, 'Six Sigma');
insert into Skills (SkillId, SkillDescription) values (512, 'Axure RP');
insert into Skills (SkillId, SkillDescription) values (513, 'New Media');
insert into Skills (SkillId, SkillDescription) values (514, 'BSI Tax Factory');
insert into Skills (SkillId, SkillDescription) values (515, 'Vulnerability Scanning');
insert into Skills (SkillId, SkillDescription) values (516, 'QMF');
insert into Skills (SkillId, SkillDescription) values (517, 'LPN');
insert into Skills (SkillId, SkillDescription) values (518, 'CMMI Level 5');
insert into Skills (SkillId, SkillDescription) values (519, 'Snoring');
insert into Skills (SkillId, SkillDescription) values (520, 'DDoS');
insert into Skills (SkillId, SkillDescription) values (521, 'Estate Jewelry');
insert into Skills (SkillId, SkillDescription) values (522, 'Fit-out');
insert into Skills (SkillId, SkillDescription) values (523, 'Apache Pig');
insert into Skills (SkillId, SkillDescription) values (524, 'DSLAM');
insert into Skills (SkillId, SkillDescription) values (525, 'BPF');
insert into Skills (SkillId, SkillDescription) values (526, 'TPX');
insert into Skills (SkillId, SkillDescription) values (527, 'Fertility');
insert into Skills (SkillId, SkillDescription) values (528, 'VTC');
insert into Skills (SkillId, SkillDescription) values (529, 'Fashion Photography');
insert into Skills (SkillId, SkillDescription) values (530, 'KRAs');
insert into Skills (SkillId, SkillDescription) values (531, 'Employee Relations');
insert into Skills (SkillId, SkillDescription) values (532, 'JDA E3');
insert into Skills (SkillId, SkillDescription) values (533, 'Company Set-up');
insert into Skills (SkillId, SkillDescription) values (534, 'HR Software');
insert into Skills (SkillId, SkillDescription) values (535, 'EOC');
insert into Skills (SkillId, SkillDescription) values (536, 'CMMI Level 5');
insert into Skills (SkillId, SkillDescription) values (537, 'Jenark');
insert into Skills (SkillId, SkillDescription) values (538, 'Yield');
insert into Skills (SkillId, SkillDescription) values (539, 'Drilling Engineering');
insert into Skills (SkillId, SkillDescription) values (540, 'CPT');
insert into Skills (SkillId, SkillDescription) values (541, 'Object Oriented Modeling');
insert into Skills (SkillId, SkillDescription) values (542, 'IEEE standards');
insert into Skills (SkillId, SkillDescription) values (543, 'Flights');
insert into Skills (SkillId, SkillDescription) values (544, 'Yamaha Digital Consoles');
insert into Skills (SkillId, SkillDescription) values (545, 'RBD');
insert into Skills (SkillId, SkillDescription) values (546, 'Kaspersky');
insert into Skills (SkillId, SkillDescription) values (547, 'Target Costing');
insert into Skills (SkillId, SkillDescription) values (548, 'Corporate Tax');
insert into Skills (SkillId, SkillDescription) values (549, 'High Performance Computing');
insert into Skills (SkillId, SkillDescription) values (550, 'PMM');
insert into Skills (SkillId, SkillDescription) values (551, 'Online Advertising');
insert into Skills (SkillId, SkillDescription) values (552, 'Oil &amp; Gas Services');
insert into Skills (SkillId, SkillDescription) values (553, 'JSF');
insert into Skills (SkillId, SkillDescription) values (554, 'iBatis');
insert into Skills (SkillId, SkillDescription) values (555, 'Aquatic Toxicology');
insert into Skills (SkillId, SkillDescription) values (556, 'BLS');
insert into Skills (SkillId, SkillDescription) values (557, 'Mortgage Banking');
insert into Skills (SkillId, SkillDescription) values (558, 'Broadcast');
insert into Skills (SkillId, SkillDescription) values (559, 'SRM');
insert into Skills (SkillId, SkillDescription) values (560, 'EEOC');
insert into Skills (SkillId, SkillDescription) values (561, 'OECD');
insert into Skills (SkillId, SkillDescription) values (562, 'Titration');
insert into Skills (SkillId, SkillDescription) values (563, 'Intercollegiate Athletics');
insert into Skills (SkillId, SkillDescription) values (564, 'Mycology');
insert into Skills (SkillId, SkillDescription) values (565, 'Corporate Tax');
insert into Skills (SkillId, SkillDescription) values (566, 'RMDS');
insert into Skills (SkillId, SkillDescription) values (567, 'Lustre');
insert into Skills (SkillId, SkillDescription) values (568, 'eGain');
insert into Skills (SkillId, SkillDescription) values (569, 'SSL');
insert into Skills (SkillId, SkillDescription) values (570, 'JDeveloper');
insert into Skills (SkillId, SkillDescription) values (571, 'WDK');
insert into Skills (SkillId, SkillDescription) values (572, 'Test Planning');
insert into Skills (SkillId, SkillDescription) values (573, 'PDA');
insert into Skills (SkillId, SkillDescription) values (574, 'XMPP');
insert into Skills (SkillId, SkillDescription) values (575, 'Furnishings');
insert into Skills (SkillId, SkillDescription) values (576, 'Bank-owned Properties');
insert into Skills (SkillId, SkillDescription) values (577, 'Certified DDI Facilitator');
insert into Skills (SkillId, SkillDescription) values (578, 'Zoho');
insert into Skills (SkillId, SkillDescription) values (579, 'Medication Therapy Management');
insert into Skills (SkillId, SkillDescription) values (580, 'Ducting');
insert into Skills (SkillId, SkillDescription) values (581, 'iWeb');
insert into Skills (SkillId, SkillDescription) values (582, 'Hibernate');
insert into Skills (SkillId, SkillDescription) values (583, 'RPAS');
insert into Skills (SkillId, SkillDescription) values (584, 'Cross-border Transactions');
insert into Skills (SkillId, SkillDescription) values (585, 'Gold');
insert into Skills (SkillId, SkillDescription) values (586, 'EBMS');
insert into Skills (SkillId, SkillDescription) values (587, 'IT Audit');
insert into Skills (SkillId, SkillDescription) values (588, 'Crystal Xcelsius');
insert into Skills (SkillId, SkillDescription) values (589, 'Android');
insert into Skills (SkillId, SkillDescription) values (590, 'Cash Handling');
insert into Skills (SkillId, SkillDescription) values (591, 'Business Intelligence Tools');
insert into Skills (SkillId, SkillDescription) values (592, 'Aerospace');
insert into Skills (SkillId, SkillDescription) values (593, 'Embedded Software');
insert into Skills (SkillId, SkillDescription) values (594, 'IEX Total View');
insert into Skills (SkillId, SkillDescription) values (595, 'Navisworks');
insert into Skills (SkillId, SkillDescription) values (596, 'Move Up Buyers');
insert into Skills (SkillId, SkillDescription) values (597, 'Tween');
insert into Skills (SkillId, SkillDescription) values (598, 'ISO 27001');
insert into Skills (SkillId, SkillDescription) values (599, 'Program Evaluation');
insert into Skills (SkillId, SkillDescription) values (600, 'Qik');
insert into Skills (SkillId, SkillDescription) values (601, 'HCM Processes &amp; Forms');
insert into Skills (SkillId, SkillDescription) values (602, 'Nikon');
insert into Skills (SkillId, SkillDescription) values (603, 'Java');
insert into Skills (SkillId, SkillDescription) values (604, 'Professional Ethics');
insert into Skills (SkillId, SkillDescription) values (605, 'Bookkeeping');
insert into Skills (SkillId, SkillDescription) values (606, 'Logic Pro');
insert into Skills (SkillId, SkillDescription) values (607, 'Jenark');
insert into Skills (SkillId, SkillDescription) values (608, 'MPBGP');
insert into Skills (SkillId, SkillDescription) values (609, 'BTS');
insert into Skills (SkillId, SkillDescription) values (610, 'FDCPA');
insert into Skills (SkillId, SkillDescription) values (611, 'FM/2');
insert into Skills (SkillId, SkillDescription) values (612, 'DTA');
insert into Skills (SkillId, SkillDescription) values (613, 'IAX');
insert into Skills (SkillId, SkillDescription) values (614, 'AJAX Toolkit');
insert into Skills (SkillId, SkillDescription) values (615, 'CTRM');
insert into Skills (SkillId, SkillDescription) values (616, 'CPOE');
insert into Skills (SkillId, SkillDescription) values (617, 'Hatha Yoga');
insert into Skills (SkillId, SkillDescription) values (618, 'Forklift Operation');
insert into Skills (SkillId, SkillDescription) values (619, 'Dunn &amp; Bradstreet');
insert into Skills (SkillId, SkillDescription) values (620, 'SnapMirror');
insert into Skills (SkillId, SkillDescription) values (621, 'TTL');
insert into Skills (SkillId, SkillDescription) values (622, 'RPD');
insert into Skills (SkillId, SkillDescription) values (623, 'CSAT');
insert into Skills (SkillId, SkillDescription) values (624, 'Company Set-up');
insert into Skills (SkillId, SkillDescription) values (625, 'Pyrometallurgy');
insert into Skills (SkillId, SkillDescription) values (626, 'Pinterest');
insert into Skills (SkillId, SkillDescription) values (627, 'Cash Flow');
insert into Skills (SkillId, SkillDescription) values (628, 'Smartstream TLM');
insert into Skills (SkillId, SkillDescription) values (629, 'QSIG');
insert into Skills (SkillId, SkillDescription) values (630, 'Shopper Marketing');
insert into Skills (SkillId, SkillDescription) values (631, 'Loss Prevention');
insert into Skills (SkillId, SkillDescription) values (632, 'GWT');
insert into Skills (SkillId, SkillDescription) values (633, 'Ducting');
insert into Skills (SkillId, SkillDescription) values (634, 'Sony HDV');
insert into Skills (SkillId, SkillDescription) values (635, 'RCCA');
insert into Skills (SkillId, SkillDescription) values (636, 'MicroStation');
insert into Skills (SkillId, SkillDescription) values (637, 'Climate Change');
insert into Skills (SkillId, SkillDescription) values (638, 'Piano Playing');
insert into Skills (SkillId, SkillDescription) values (639, 'IT Solutions');
insert into Skills (SkillId, SkillDescription) values (640, 'RPD');
insert into Skills (SkillId, SkillDescription) values (641, 'Algebra');
insert into Skills (SkillId, SkillDescription) values (642, 'XOG');
insert into Skills (SkillId, SkillDescription) values (643, 'Awareness Raising');
insert into Skills (SkillId, SkillDescription) values (644, 'z/VM');
insert into Skills (SkillId, SkillDescription) values (645, 'Interior Architecture');
insert into Skills (SkillId, SkillDescription) values (646, 'Gastroenterology');
insert into Skills (SkillId, SkillDescription) values (647, 'MBE');
insert into Skills (SkillId, SkillDescription) values (648, 'C-TPAT');
insert into Skills (SkillId, SkillDescription) values (649, 'RAN');
insert into Skills (SkillId, SkillDescription) values (650, 'Kodaly');
insert into Skills (SkillId, SkillDescription) values (651, 'Critical Care');
insert into Skills (SkillId, SkillDescription) values (652, 'Business Analysis');
insert into Skills (SkillId, SkillDescription) values (653, 'Peer Tutoring');
insert into Skills (SkillId, SkillDescription) values (654, 'European Computer Driving Licence');
insert into Skills (SkillId, SkillDescription) values (655, 'Feature Articles');
insert into Skills (SkillId, SkillDescription) values (656, 'Power Electronics');
insert into Skills (SkillId, SkillDescription) values (657, 'Trade Shows');
insert into Skills (SkillId, SkillDescription) values (658, 'Titration');
insert into Skills (SkillId, SkillDescription) values (659, 'DLPAR');
insert into Skills (SkillId, SkillDescription) values (660, 'Business Objects');
insert into Skills (SkillId, SkillDescription) values (661, 'PPMS');
insert into Skills (SkillId, SkillDescription) values (662, 'Product Management');
insert into Skills (SkillId, SkillDescription) values (663, 'IFR');
insert into Skills (SkillId, SkillDescription) values (664, 'JSTL');
insert into Skills (SkillId, SkillDescription) values (665, 'QA Automation');
insert into Skills (SkillId, SkillDescription) values (666, 'CDL Class B');
insert into Skills (SkillId, SkillDescription) values (667, 'Cell');
insert into Skills (SkillId, SkillDescription) values (668, 'HP Blade');
insert into Skills (SkillId, SkillDescription) values (669, 'Psychosocial');
insert into Skills (SkillId, SkillDescription) values (670, 'Offshore Oil &amp; Gas');
insert into Skills (SkillId, SkillDescription) values (671, 'Outdoor Advertising');
insert into Skills (SkillId, SkillDescription) values (672, 'Westlaw');
insert into Skills (SkillId, SkillDescription) values (673, 'Autism Spectrum Disorders');
insert into Skills (SkillId, SkillDescription) values (674, 'RVM');
insert into Skills (SkillId, SkillDescription) values (675, 'Analytical Ultracentrifugation');
insert into Skills (SkillId, SkillDescription) values (676, 'Space Planning');
insert into Skills (SkillId, SkillDescription) values (677, 'Bonds');
insert into Skills (SkillId, SkillDescription) values (678, 'JBPM');
insert into Skills (SkillId, SkillDescription) values (679, 'Visual Communication');
insert into Skills (SkillId, SkillDescription) values (680, 'Grocery');
insert into Skills (SkillId, SkillDescription) values (681, 'Fixed Income');
insert into Skills (SkillId, SkillDescription) values (682, 'LVS');
insert into Skills (SkillId, SkillDescription) values (683, 'qRT-PCR');
insert into Skills (SkillId, SkillDescription) values (684, 'Avaya Technologies');
insert into Skills (SkillId, SkillDescription) values (685, 'Windows XP');
insert into Skills (SkillId, SkillDescription) values (686, 'XenClient');
insert into Skills (SkillId, SkillDescription) values (687, 'HST');
insert into Skills (SkillId, SkillDescription) values (688, 'Oil Sands');
insert into Skills (SkillId, SkillDescription) values (689, 'Psychosocial');
insert into Skills (SkillId, SkillDescription) values (690, 'MVPN');
insert into Skills (SkillId, SkillDescription) values (691, 'Concept HDL');
insert into Skills (SkillId, SkillDescription) values (692, 'HDI');
insert into Skills (SkillId, SkillDescription) values (693, 'Open XML');
insert into Skills (SkillId, SkillDescription) values (694, 'EOS');
insert into Skills (SkillId, SkillDescription) values (695, 'Federal Law Enforcement');
insert into Skills (SkillId, SkillDescription) values (696, 'VSAM');
insert into Skills (SkillId, SkillDescription) values (697, 'Gmail');
insert into Skills (SkillId, SkillDescription) values (698, 'Merchandising');
insert into Skills (SkillId, SkillDescription) values (699, 'ODE');
insert into Skills (SkillId, SkillDescription) values (700, 'LN');
insert into Skills (SkillId, SkillDescription) values (701, 'PFT');
insert into Skills (SkillId, SkillDescription) values (702, 'Background Checks');
insert into Skills (SkillId, SkillDescription) values (703, 'NFL');
insert into Skills (SkillId, SkillDescription) values (704, 'Operational Risk Management');
insert into Skills (SkillId, SkillDescription) values (705, 'NDE');
insert into Skills (SkillId, SkillDescription) values (706, 'Online Gambling');
insert into Skills (SkillId, SkillDescription) values (707, 'Human Resource Development');
insert into Skills (SkillId, SkillDescription) values (708, 'MDB');
insert into Skills (SkillId, SkillDescription) values (709, 'Omnis');
insert into Skills (SkillId, SkillDescription) values (710, 'JSON-RPC');
insert into Skills (SkillId, SkillDescription) values (711, 'Employment Law');
insert into Skills (SkillId, SkillDescription) values (712, 'EBPP');
insert into Skills (SkillId, SkillDescription) values (713, 'MMIS');
insert into Skills (SkillId, SkillDescription) values (714, 'TCLEOSE Instruction');
insert into Skills (SkillId, SkillDescription) values (715, 'Eyeon Fusion');
insert into Skills (SkillId, SkillDescription) values (716, 'VBScript');
insert into Skills (SkillId, SkillDescription) values (717, 'WLAN');
insert into Skills (SkillId, SkillDescription) values (718, 'IT Audit');
insert into Skills (SkillId, SkillDescription) values (719, 'NRP Instruction');
insert into Skills (SkillId, SkillDescription) values (720, 'TDR');
insert into Skills (SkillId, SkillDescription) values (721, 'FNMA');
insert into Skills (SkillId, SkillDescription) values (722, 'Dogs');
insert into Skills (SkillId, SkillDescription) values (723, 'MSI');
insert into Skills (SkillId, SkillDescription) values (724, 'Hospitality Management');
insert into Skills (SkillId, SkillDescription) values (725, 'PFD');
insert into Skills (SkillId, SkillDescription) values (726, 'Food');
insert into Skills (SkillId, SkillDescription) values (727, 'Foreign Policy');
insert into Skills (SkillId, SkillDescription) values (728, 'Biochemistry');
insert into Skills (SkillId, SkillDescription) values (729, 'Payments');
insert into Skills (SkillId, SkillDescription) values (730, 'USDA Rural Housing');
insert into Skills (SkillId, SkillDescription) values (731, 'MSS');
insert into Skills (SkillId, SkillDescription) values (732, 'FPA');
insert into Skills (SkillId, SkillDescription) values (733, 'Construction Safety');
insert into Skills (SkillId, SkillDescription) values (734, 'EIFS');
insert into Skills (SkillId, SkillDescription) values (735, 'Food');
insert into Skills (SkillId, SkillDescription) values (736, 'Ethnography');
insert into Skills (SkillId, SkillDescription) values (737, 'Lithium-ion Batteries');
insert into Skills (SkillId, SkillDescription) values (738, 'FFE');
insert into Skills (SkillId, SkillDescription) values (739, 'Lync');
insert into Skills (SkillId, SkillDescription) values (740, 'Childcare');
insert into Skills (SkillId, SkillDescription) values (741, 'Japanese Language Proficiency Test');
insert into Skills (SkillId, SkillDescription) values (742, 'TDMA');
insert into Skills (SkillId, SkillDescription) values (743, 'Ocean Freight');
insert into Skills (SkillId, SkillDescription) values (744, 'High Yield');
insert into Skills (SkillId, SkillDescription) values (745, 'Events Coordination');
insert into Skills (SkillId, SkillDescription) values (746, 'DCS');
insert into Skills (SkillId, SkillDescription) values (747, 'RTL Verification');
insert into Skills (SkillId, SkillDescription) values (748, 'MRSA');
insert into Skills (SkillId, SkillDescription) values (749, 'GDI+');
insert into Skills (SkillId, SkillDescription) values (750, 'SEP IRA');
insert into Skills (SkillId, SkillDescription) values (751, 'Ultrasound');
insert into Skills (SkillId, SkillDescription) values (752, 'BMC Patrol');
insert into Skills (SkillId, SkillDescription) values (753, 'Tutoring');
insert into Skills (SkillId, SkillDescription) values (754, 'MTP3');
insert into Skills (SkillId, SkillDescription) values (755, 'Nutrition');
insert into Skills (SkillId, SkillDescription) values (756, 'Executive Coaching');
insert into Skills (SkillId, SkillDescription) values (757, 'Cisco UCS');
insert into Skills (SkillId, SkillDescription) values (758, 'TPT');
insert into Skills (SkillId, SkillDescription) values (759, 'Ownership');
insert into Skills (SkillId, SkillDescription) values (760, 'Gx');
insert into Skills (SkillId, SkillDescription) values (761, 'International Economics');
insert into Skills (SkillId, SkillDescription) values (762, 'EEOC');
insert into Skills (SkillId, SkillDescription) values (763, 'NDMP');
insert into Skills (SkillId, SkillDescription) values (764, 'VMware');
insert into Skills (SkillId, SkillDescription) values (765, 'Hlookups');
insert into Skills (SkillId, SkillDescription) values (766, 'HDV');
insert into Skills (SkillId, SkillDescription) values (767, 'LR');
insert into Skills (SkillId, SkillDescription) values (768, 'AWS CWI');
insert into Skills (SkillId, SkillDescription) values (769, 'GFI');
insert into Skills (SkillId, SkillDescription) values (770, 'OOS');
insert into Skills (SkillId, SkillDescription) values (771, 'Workshop Facilitation');
insert into Skills (SkillId, SkillDescription) values (772, 'Xilinx ISE');
insert into Skills (SkillId, SkillDescription) values (773, 'LLU');
insert into Skills (SkillId, SkillDescription) values (774, 'Microsoft Word');
insert into Skills (SkillId, SkillDescription) values (775, 'Buyer Representation');
insert into Skills (SkillId, SkillDescription) values (776, 'ERD');
insert into Skills (SkillId, SkillDescription) values (777, 'Middle Office');
insert into Skills (SkillId, SkillDescription) values (778, 'KPO');
insert into Skills (SkillId, SkillDescription) values (779, 'VLR');
insert into Skills (SkillId, SkillDescription) values (780, 'DSI');
insert into Skills (SkillId, SkillDescription) values (781, 'Employee Relations');
insert into Skills (SkillId, SkillDescription) values (782, 'xCAT');
insert into Skills (SkillId, SkillDescription) values (783, 'Process Automation');
insert into Skills (SkillId, SkillDescription) values (784, 'SQLite');
insert into Skills (SkillId, SkillDescription) values (785, 'SG&amp;A');
insert into Skills (SkillId, SkillDescription) values (786, 'Jerseys');
insert into Skills (SkillId, SkillDescription) values (787, 'TPA');
insert into Skills (SkillId, SkillDescription) values (788, 'Motivational Interviewing');
insert into Skills (SkillId, SkillDescription) values (789, 'WCDMA');
insert into Skills (SkillId, SkillDescription) values (790, 'Equity Trading');
insert into Skills (SkillId, SkillDescription) values (791, 'DDR3');
insert into Skills (SkillId, SkillDescription) values (792, 'Billing Systems');
insert into Skills (SkillId, SkillDescription) values (793, 'SharePoint');
insert into Skills (SkillId, SkillDescription) values (794, 'Residential Mortgages');
insert into Skills (SkillId, SkillDescription) values (795, 'Yoga');
insert into Skills (SkillId, SkillDescription) values (796, 'Internet TV');
insert into Skills (SkillId, SkillDescription) values (797, '.htaccess');
insert into Skills (SkillId, SkillDescription) values (798, 'Architecture');
insert into Skills (SkillId, SkillDescription) values (799, 'BGA');
insert into Skills (SkillId, SkillDescription) values (800, 'Journalism');
insert into Skills (SkillId, SkillDescription) values (801, 'Oxygen XML Editor');
insert into Skills (SkillId, SkillDescription) values (802, 'CNC Operation');
insert into Skills (SkillId, SkillDescription) values (803, 'Lifestyle');
insert into Skills (SkillId, SkillDescription) values (804, 'ERP Implementations');
insert into Skills (SkillId, SkillDescription) values (805, 'Landlords');
insert into Skills (SkillId, SkillDescription) values (806, 'Westlaw');
insert into Skills (SkillId, SkillDescription) values (807, 'EE4');
insert into Skills (SkillId, SkillDescription) values (808, 'Robotics');
insert into Skills (SkillId, SkillDescription) values (809, 'IEC 61131-3');
insert into Skills (SkillId, SkillDescription) values (810, 'MS Reporting Services');
insert into Skills (SkillId, SkillDescription) values (811, 'Contract Negotiation');
insert into Skills (SkillId, SkillDescription) values (812, 'Islamic Finance');
insert into Skills (SkillId, SkillDescription) values (813, 'Special Events');
insert into Skills (SkillId, SkillDescription) values (814, 'Yammer');
insert into Skills (SkillId, SkillDescription) values (815, 'BS7799');
insert into Skills (SkillId, SkillDescription) values (816, 'EES');
insert into Skills (SkillId, SkillDescription) values (817, 'Pro Tools');
insert into Skills (SkillId, SkillDescription) values (818, 'FF&amp;E Procurement');
insert into Skills (SkillId, SkillDescription) values (819, 'JD Edwards');
insert into Skills (SkillId, SkillDescription) values (820, 'Business Ethics');
insert into Skills (SkillId, SkillDescription) values (821, 'JNCIP');
insert into Skills (SkillId, SkillDescription) values (822, 'Music Industry');
insert into Skills (SkillId, SkillDescription) values (823, 'VMware Fusion');
insert into Skills (SkillId, SkillDescription) values (824, 'FTC');
insert into Skills (SkillId, SkillDescription) values (825, 'SSCP');
insert into Skills (SkillId, SkillDescription) values (826, 'KDB');
insert into Skills (SkillId, SkillDescription) values (827, 'Air Conditioning');
insert into Skills (SkillId, SkillDescription) values (828, 'Government');
insert into Skills (SkillId, SkillDescription) values (829, 'HSE auditing');
insert into Skills (SkillId, SkillDescription) values (830, 'QlikView Development');
insert into Skills (SkillId, SkillDescription) values (831, 'Luxury');
insert into Skills (SkillId, SkillDescription) values (832, 'IXIA');
insert into Skills (SkillId, SkillDescription) values (833, 'VDSL2');
insert into Skills (SkillId, SkillDescription) values (834, 'Sickness Absence Management');
insert into Skills (SkillId, SkillDescription) values (835, 'WebLogic');
insert into Skills (SkillId, SkillDescription) values (836, 'Supply Chain Optimization');
insert into Skills (SkillId, SkillDescription) values (837, 'MVS');
insert into Skills (SkillId, SkillDescription) values (838, 'MYOB');
insert into Skills (SkillId, SkillDescription) values (839, 'Phase II ESA');
insert into Skills (SkillId, SkillDescription) values (840, 'Drilling');
insert into Skills (SkillId, SkillDescription) values (841, 'PostgreSQL');
insert into Skills (SkillId, SkillDescription) values (842, 'Capacity Building');
insert into Skills (SkillId, SkillDescription) values (843, 'JFace');
insert into Skills (SkillId, SkillDescription) values (844, 'Bartending');
insert into Skills (SkillId, SkillDescription) values (845, 'Black Belt');
insert into Skills (SkillId, SkillDescription) values (846, 'Aerial Lifts');
insert into Skills (SkillId, SkillDescription) values (847, 'FTTP');
insert into Skills (SkillId, SkillDescription) values (848, 'AVEVA PDMS');
insert into Skills (SkillId, SkillDescription) values (849, 'Medical-Surgical');
insert into Skills (SkillId, SkillDescription) values (850, 'IED');
insert into Skills (SkillId, SkillDescription) values (851, 'E-zines');
insert into Skills (SkillId, SkillDescription) values (852, 'HCPCS');
insert into Skills (SkillId, SkillDescription) values (853, 'DVD');
insert into Skills (SkillId, SkillDescription) values (854, 'Global Health');
insert into Skills (SkillId, SkillDescription) values (855, 'Www');
insert into Skills (SkillId, SkillDescription) values (856, 'IPTV');
insert into Skills (SkillId, SkillDescription) values (857, 'HVAC Controls');
insert into Skills (SkillId, SkillDescription) values (858, 'Time Series Analysis');
insert into Skills (SkillId, SkillDescription) values (859, 'GNU Radio');
insert into Skills (SkillId, SkillDescription) values (860, 'SSAE 16');
insert into Skills (SkillId, SkillDescription) values (861, 'Fermentation');
insert into Skills (SkillId, SkillDescription) values (862, 'Nginx');
insert into Skills (SkillId, SkillDescription) values (863, 'Design Patterns');
insert into Skills (SkillId, SkillDescription) values (864, 'Work Very Well with Others');
insert into Skills (SkillId, SkillDescription) values (865, 'vRanger');
insert into Skills (SkillId, SkillDescription) values (866, 'GMLAN');
insert into Skills (SkillId, SkillDescription) values (867, 'Getting to Yes');
insert into Skills (SkillId, SkillDescription) values (868, 'BFSI');
insert into Skills (SkillId, SkillDescription) values (869, 'Guided Imagery');
insert into Skills (SkillId, SkillDescription) values (870, 'MV');
insert into Skills (SkillId, SkillDescription) values (871, 'RELAX NG');
insert into Skills (SkillId, SkillDescription) values (872, 'Board of Directors');
insert into Skills (SkillId, SkillDescription) values (873, 'Formation Evaluation');
insert into Skills (SkillId, SkillDescription) values (874, 'MFG-Pro');
insert into Skills (SkillId, SkillDescription) values (875, 'Bands');
insert into Skills (SkillId, SkillDescription) values (876, 'Technical Illustration');
insert into Skills (SkillId, SkillDescription) values (877, 'Microsoft Technologies');
insert into Skills (SkillId, SkillDescription) values (878, 'Yoga Instruction');
insert into Skills (SkillId, SkillDescription) values (879, 'USDA');
insert into Skills (SkillId, SkillDescription) values (880, 'JTA');
insert into Skills (SkillId, SkillDescription) values (881, 'Blended Learning');
insert into Skills (SkillId, SkillDescription) values (882, 'NDIS');
insert into Skills (SkillId, SkillDescription) values (883, 'Chronic Illness');
insert into Skills (SkillId, SkillDescription) values (884, 'NLog');
insert into Skills (SkillId, SkillDescription) values (885, 'Sports Writing');
insert into Skills (SkillId, SkillDescription) values (886, 'CNN Pathfire');
insert into Skills (SkillId, SkillDescription) values (887, 'AHA');
insert into Skills (SkillId, SkillDescription) values (888, 'JTIDS');
insert into Skills (SkillId, SkillDescription) values (889, 'Thermal Oxidation');
insert into Skills (SkillId, SkillDescription) values (890, 'MPIO');
insert into Skills (SkillId, SkillDescription) values (891, 'Substance Abuse Prevention');
insert into Skills (SkillId, SkillDescription) values (892, 'IKB');
insert into Skills (SkillId, SkillDescription) values (893, 'Baan ERP');
insert into Skills (SkillId, SkillDescription) values (894, 'CCTV');
insert into Skills (SkillId, SkillDescription) values (895, 'Residential Homes');
insert into Skills (SkillId, SkillDescription) values (896, 'Sony Vegas');
insert into Skills (SkillId, SkillDescription) values (897, 'Asset Protection');
insert into Skills (SkillId, SkillDescription) values (898, 'SAP ERP');
insert into Skills (SkillId, SkillDescription) values (899, 'RFID+');
insert into Skills (SkillId, SkillDescription) values (900, 'DFU');
insert into Skills (SkillId, SkillDescription) values (901, 'Social Justice');
insert into Skills (SkillId, SkillDescription) values (902, 'Freight Forwarding');
insert into Skills (SkillId, SkillDescription) values (903, 'Nintex');
insert into Skills (SkillId, SkillDescription) values (904, 'VXI');
insert into Skills (SkillId, SkillDescription) values (905, 'NCBI');
insert into Skills (SkillId, SkillDescription) values (906, 'Veterinary');
insert into Skills (SkillId, SkillDescription) values (907, 'MPBGP');
insert into Skills (SkillId, SkillDescription) values (908, 'Canon XL2');
insert into Skills (SkillId, SkillDescription) values (909, 'NCover');
insert into Skills (SkillId, SkillDescription) values (910, 'FCL');
insert into Skills (SkillId, SkillDescription) values (911, 'NIR Spectroscopy');
insert into Skills (SkillId, SkillDescription) values (912, 'FSL');
insert into Skills (SkillId, SkillDescription) values (913, 'Pipelines');
insert into Skills (SkillId, SkillDescription) values (914, 'HTML Help Workshop');
insert into Skills (SkillId, SkillDescription) values (915, 'PMAs');
insert into Skills (SkillId, SkillDescription) values (916, 'Smartstream TLM');
insert into Skills (SkillId, SkillDescription) values (917, 'Myofascial Release Therapy');
insert into Skills (SkillId, SkillDescription) values (918, 'Ergonomics');
insert into Skills (SkillId, SkillDescription) values (919, 'Agile Application Development');
insert into Skills (SkillId, SkillDescription) values (920, 'Workforce Management');
insert into Skills (SkillId, SkillDescription) values (921, 'Employee Relations');
insert into Skills (SkillId, SkillDescription) values (922, 'Water Management');
insert into Skills (SkillId, SkillDescription) values (923, 'MPR');
insert into Skills (SkillId, SkillDescription) values (924, 'Low Voltage');
insert into Skills (SkillId, SkillDescription) values (925, 'UED');
insert into Skills (SkillId, SkillDescription) values (926, 'WTP');
insert into Skills (SkillId, SkillDescription) values (927, 'Allergy');
insert into Skills (SkillId, SkillDescription) values (928, 'Analytical Chemistry');
insert into Skills (SkillId, SkillDescription) values (929, 'iGrafx');
insert into Skills (SkillId, SkillDescription) values (930, 'Teeth Whitening');
insert into Skills (SkillId, SkillDescription) values (931, 'Ownership');
insert into Skills (SkillId, SkillDescription) values (932, 'DVD');
insert into Skills (SkillId, SkillDescription) values (933, 'RHIT');
insert into Skills (SkillId, SkillDescription) values (934, 'PVElite');
insert into Skills (SkillId, SkillDescription) values (935, 'UG');
insert into Skills (SkillId, SkillDescription) values (936, 'Utility Systems');
insert into Skills (SkillId, SkillDescription) values (937, 'MMC');
insert into Skills (SkillId, SkillDescription) values (938, 'Validation');
insert into Skills (SkillId, SkillDescription) values (939, 'Pivot Tables');
insert into Skills (SkillId, SkillDescription) values (940, 'Laptops');
insert into Skills (SkillId, SkillDescription) values (941, 'TMJ Dysfunction');
insert into Skills (SkillId, SkillDescription) values (942, 'KWI');
insert into Skills (SkillId, SkillDescription) values (943, 'Tourism Management');
insert into Skills (SkillId, SkillDescription) values (944, 'MBAL');
insert into Skills (SkillId, SkillDescription) values (945, 'Zoo');
insert into Skills (SkillId, SkillDescription) values (946, 'MS Integration Services');
insert into Skills (SkillId, SkillDescription) values (947, 'MQL4');
insert into Skills (SkillId, SkillDescription) values (948, 'Contemporary Art');
insert into Skills (SkillId, SkillDescription) values (949, 'LyX');
insert into Skills (SkillId, SkillDescription) values (950, 'FBO');
insert into Skills (SkillId, SkillDescription) values (951, 'JMeter');
insert into Skills (SkillId, SkillDescription) values (952, 'Wiring');
insert into Skills (SkillId, SkillDescription) values (953, 'Citrix XenApp');
insert into Skills (SkillId, SkillDescription) values (954, 'Jeans');
insert into Skills (SkillId, SkillDescription) values (955, 'QuarkXPress');
insert into Skills (SkillId, SkillDescription) values (956, 'DVD Replication');
insert into Skills (SkillId, SkillDescription) values (957, 'Piano Education');
insert into Skills (SkillId, SkillDescription) values (958, 'DTR');
insert into Skills (SkillId, SkillDescription) values (959, 'Egyptology');
insert into Skills (SkillId, SkillDescription) values (960, 'PMP');
insert into Skills (SkillId, SkillDescription) values (961, 'DDI Certified');
insert into Skills (SkillId, SkillDescription) values (962, 'Tgrid');
insert into Skills (SkillId, SkillDescription) values (963, 'Supply Chain');
insert into Skills (SkillId, SkillDescription) values (964, 'DDD');
insert into Skills (SkillId, SkillDescription) values (965, 'Contact Centers');
insert into Skills (SkillId, SkillDescription) values (966, 'Applied Behavior Analysis');
insert into Skills (SkillId, SkillDescription) values (967, 'NCSS');
insert into Skills (SkillId, SkillDescription) values (968, 'Twisted');
insert into Skills (SkillId, SkillDescription) values (969, 'RCM');
insert into Skills (SkillId, SkillDescription) values (970, 'DFLSS');
insert into Skills (SkillId, SkillDescription) values (971, 'Hydraulics');
insert into Skills (SkillId, SkillDescription) values (972, 'DTC');
insert into Skills (SkillId, SkillDescription) values (973, 'DHTML');
insert into Skills (SkillId, SkillDescription) values (974, 'Zillow');
insert into Skills (SkillId, SkillDescription) values (975, 'uCOS');
insert into Skills (SkillId, SkillDescription) values (976, 'Kohana');
insert into Skills (SkillId, SkillDescription) values (977, 'EU Competition Law');
insert into Skills (SkillId, SkillDescription) values (978, 'WF');
insert into Skills (SkillId, SkillDescription) values (979, 'DXX');
insert into Skills (SkillId, SkillDescription) values (980, 'Police');
insert into Skills (SkillId, SkillDescription) values (981, 'LMDS');
insert into Skills (SkillId, SkillDescription) values (982, 'Personal Injury');
insert into Skills (SkillId, SkillDescription) values (983, 'Fashion GPS');
insert into Skills (SkillId, SkillDescription) values (984, 'Type 2 Diabetes');
insert into Skills (SkillId, SkillDescription) values (985, 'Object Oriented Design');
insert into Skills (SkillId, SkillDescription) values (986, 'EGPRS');
insert into Skills (SkillId, SkillDescription) values (987, 'iWeb');
insert into Skills (SkillId, SkillDescription) values (988, 'Public Sector');
insert into Skills (SkillId, SkillDescription) values (989, 'NMLS');
insert into Skills (SkillId, SkillDescription) values (990, 'CCDA');
insert into Skills (SkillId, SkillDescription) values (991, 'Lynx');
insert into Skills (SkillId, SkillDescription) values (992, 'EOC');
insert into Skills (SkillId, SkillDescription) values (993, 'Wheat');
insert into Skills (SkillId, SkillDescription) values (994, 'Erosion Control');
insert into Skills (SkillId, SkillDescription) values (995, 'Nuclear');
insert into Skills (SkillId, SkillDescription) values (996, 'EMS');
insert into Skills (SkillId, SkillDescription) values (997, 'ICDL');
insert into Skills (SkillId, SkillDescription) values (998, 'CADS RC');
insert into Skills (SkillId, SkillDescription) values (999, 'White Papers');
insert into Skills (SkillId, SkillDescription) values (1000, 'pfSense');
